# Generated by Django 5.2.10 on 2026-02-02 19:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'email_recipients',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='sendgrid', max_length=50)),
                ('from_email', models.EmailField(default='', max_length=254)),
                ('from_name', models.CharField(default='', max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mailgun_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mailgun_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('mailgun_region', models.CharField(default='us', max_length=50, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_secure', models.BooleanField(default=False)),
                ('is_configured', models.BooleanField(default=False)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('telegram_notifications_enabled', models.BooleanField(default=False)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'mail_config',
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('recipient_ids', models.JSONField(default=list)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delay_seconds', models.IntegerField(default=0)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('template', models.ForeignKey(db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emailtemplate')),
            ],
            options={
                'db_table': 'email_campaigns',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, to='api.emailcampaign')),
                ('recipient', models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, to='api.emailrecipient')),
            ],
            options={
                'db_table': 'email_logs',
                'indexes': [models.Index(fields=['campaign'], name='email_logs_campaig_025547_idx'), models.Index(fields=['recipient'], name='email_logs_recipie_e1d866_idx')],
            },
        ),
    ]
