# Generated by Django 5.2.10 on 2026-02-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailconfig',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='twilio_from_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
