# Generated by Django 5.2.10 on 2026-02-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailcampaign_click_count_emailcampaign_open_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecipient',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
