# Generated by Django 5.2.10 on 2026-02-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_emailrecipient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailconfig',
            name='from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='mailconfig',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
