# Generated by Django 5.2.10 on 2026-02-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_securitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='attempt_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='review_status',
            field=models.CharField(default='unreviewed', max_length=50),
        ),
    ]
